# Generated by Django 5.2.3 on 2025-08-01 18:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(max_length=100, unique=True)),
                ('pos_count', models.IntegerField()),
                ('neg_count', models.IntegerField()),
                ('neutral_count', models.IntegerField()),
                ('overall_description', models.CharField(max_length=1000)),
                ('input_file', models.FileField(upload_to='uploads/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])])),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
