# Generated by Django 5.2.3 on 2025-08-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overall_file_sent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overallsentiment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='overallsentiment',
            name='overall_description',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='overallsentiment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
